### ISSUE TITLE
Preprocessing service error

### ISSUE THREAD

**Issue by macagari** [fandangOrg/fandango#83]
Yesterday we realized that there are issue with the preprocessing. 
I'll paste the error on my console 

Traceback (most recent call last):
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/camila/projects/fandango-fake-news/fake_news_detection/test/services_test.py", line 165, in <module>
    news_preprocessed = preprocessing(raw_article)
  File "/home/camila/projects/fandango-fake-news/fake_news_detection/test/services_test.py", line 127, in preprocessing
    response = u.post(data=j, headers=headers)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/ds4biz_commons/utils/requests_utils.py", line 55, in post
    resp = requests.post(self.__base,**args)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/camila/projects/fandango-fake-news/venv/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by macagari** [comment]
The article I sent to the service
response crawling service {'data': {'authors': [], 'date_created': '2020-12-03T10:42:59Z', 'date_modified': '2020-12-03T10:42:59Z', 'date_published': '2020-12-01T00:00:00Z', 'description': "Siria: Ong, più di 16mila uccisi in carceri governo dal 2011, 'Morti sotto tortura', ci sono anche donne e minorenni, , Cronaca, Ansa", 'identifier': '5e9b12b2f0d378b424a5461c516aabc24ab4efc4d630340ee6bdbbaa54dfa132052f7bc8608c0047287771f279a9f69646d2695ae505cf90b2dcbd2785954c5b', 'images': ['http://www.ansamed.info/ansamed/en/images/banner/banner_300x60_ahram_en.jpg', 'http://www.ansamed.info/ansamed/images/banner_300x157_infomigrants.jpg', 'http://www.ansamed.info/webimages/foto_large/2020/12/1/6087f6f25260fed1ac820ba1c147eaf5.jpg', 'http://www.ansamed.info/ansamed/en/images/banner/banner_300x60_mediterranea1.gif', 'http://www.ansamed.info/ansamed/images/youtube_icon.png', 'http://b.scorecardresearch.com/p?c1=2&c2=18389568&cv=2.0&cj=1', 'http://www.ansamed.info/ansamed/images/dailyMotion_icon.png', 'http://www.ansamed.info/ansamed/banner/banner_300x50_trend4trend.png', 'http://www.ansamed.info/ansamed/en/images/banner/banner_300x60_apsfr.png', 'http://www.ansamed.info/ansamed/images/facebook_icon.png', 'http://www.ansamed.info/ansamed/en/images/banner/banner_300x60_tap.png', 'http://www.ansamed.info/ansamed/images/italia.jpg', 'http://www.ansamed.info/ansamed/banner/banner234x90_medegolfo.gif', 'http://www.ansamed.info/ansamed/en/images/banner/banner_300x60_aman.jpg', 'http://www.ansamed.info/canale_viaggiart/img/banner/banner_300x80_ansaviaggiart.gif', 'http://www.ansamed.info/ansamed/images/twitter_icon.png', 'http://www.ansamed.info/ansamed/en/images/banner/banner_300x60_wam.png', 'http://www.ansamed.info/ansamed/images/banner_300x73_tunisair_it.png', 'http://www.ansamed.info/ansamed/images/rss_icon.png', 'http://www.ansamed.info/ansamed/banner/FOMG1_S1_conf_only-event_300x60px_ITA_Ans12mpx.jpg', 'http://www.ansamed.info/ansamed/images/banner_300x120_italian_industry.png'], 'keywords': ['governo', 'di', 'carceri', 'siria', 'uccisi', 'cronaca', 'più', 'ansamed', 'dal', 'ong'], 'language': '', 'publish_date_estimated': 'no', 'source_domain': 'www.ansamed.info', 'spider': 'online', 'summary': '', 'text': '', 'texthash': ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'], 'title': 'Siria: Ong, più di 16mila uccisi in carceri governo dal 2011 - Cronaca - ANSAMed', 'top_image': 'http://www.ansamed.info/webimages/foto_large/2020/12/1/6087f6f25260fed1ac820ba1c147eaf5.jpg', 'url': 'http://www.ansamed.info/ansamed/it/notizie/rubriche/cronaca/2020/12/01/siria-ong-piu-di-16mila-uccisi-in-carceri-governo-dal-2011_998e12b1-36a0-4c27-9e0d-5cc8972e5ee0.html', 'videos': []}, 'message': 'Successful Operation', 'status': 200}

**Comment by dmgutierrez** [comment]
It is related with the time that Flair needs to perform the prediction for the NER extraction, either we go to spacy or you should increase the timeout of your request
